using System.Text;
using System.Text.Json.Nodes;
using System.Globalization;

var options = GeneratorOptions.Parse(args);

Directory.CreateDirectory(options.OutputDirectory);
CleanGeneratedDirectory(options.OutputDirectory);

using var http = new HttpClient();
var json = await http.GetStringAsync(options.IrUrl);
var ir = JsonNode.Parse(json)?.AsObject() ?? throw new InvalidOperationException("Failed to parse ir.json.");

GenerateHeader(options.OutputDirectory, options);

var commonStructs = ir["commonStructs"]?.AsArray() ?? [];
var generationContext = BuildGenerationContext(commonStructs);

GenerateCommonStructs(options.OutputDirectory, commonStructs, generationContext, options);
GenerateApiTypes(options.OutputDirectory, ir["apiCategories"]?.AsArray() ?? [], options);

Console.WriteLine($"Generated model files into: {options.OutputDirectory}");

static void CleanGeneratedDirectory(string generatedDir)
{
    if (!Directory.Exists(generatedDir))
    {
        return;
    }

    foreach (var file in Directory.EnumerateFiles(generatedDir, "*.cs", SearchOption.AllDirectories))
    {
        File.Delete(file);
    }

    foreach (var directory in Directory.EnumerateDirectories(generatedDir, "*", SearchOption.AllDirectories)
                 .OrderByDescending(x => x.Length))
    {
        if (!Directory.EnumerateFileSystemEntries(directory).Any())
        {
            Directory.Delete(directory);
        }
    }
}

static void GenerateHeader(string generatedDir, GeneratorOptions options)
{
    var path = Path.Combine(generatedDir, "_GeneratedInfo.cs");
    WriteFile(path, $$"""
// <auto-generated />
#nullable enable
namespace {{options.GeneratedRootNamespace}};

internal static class GeneratedInfo
{
    public const string Source = "{{options.IrSourceName}}";
}
""");
}

static GenerationContext BuildGenerationContext(JsonArray commonStructs)
{
    var unionMembers = new Dictionary<string, HashSet<string>>(StringComparer.Ordinal);
    var referencedInterfaces = new Dictionary<string, HashSet<string>>(StringComparer.Ordinal);

    foreach (var item in commonStructs.OfType<JsonObject>())
    {
        var name = item["name"]?.GetValue<string>();
        var structType = item["structType"]?.GetValue<string>();
        if (string.IsNullOrWhiteSpace(name) || structType != "union")
        {
            continue;
        }

        var members = new HashSet<string>(StringComparer.Ordinal);
        unionMembers[name] = members;

        if (item["unionType"]?.GetValue<string>() == "plain")
        {
            foreach (var derived in item["derivedStructs"]?.AsArray()?.OfType<JsonObject>() ?? [])
            {
                var tagValue = derived["tagValue"]?.GetValue<string>() ?? string.Empty;
                if (!string.IsNullOrWhiteSpace(tagValue))
                {
                    members.Add($"{SnakeToPascal(tagValue)}{name}");
                }
            }
        }
        else
        {
            foreach (var derived in item["derivedTypes"]?.AsArray()?.OfType<JsonObject>() ?? [])
            {
                var tagValue = derived["tagValue"]?.GetValue<string>() ?? string.Empty;
                var derivingType = derived["derivingType"]?.GetValue<string>() ?? "struct";
                if (derivingType == "struct" && !string.IsNullOrWhiteSpace(tagValue))
                {
                    members.Add($"{SnakeToPascal(tagValue)}{name}");
                }
            }
        }
    }

    foreach (var item in commonStructs.OfType<JsonObject>())
    {
        var name = item["name"]?.GetValue<string>();
        var structType = item["structType"]?.GetValue<string>();
        if (string.IsNullOrWhiteSpace(name) || structType != "union" || item["unionType"]?.GetValue<string>() != "withData")
        {
            continue;
        }

        foreach (var derived in item["derivedTypes"]?.AsArray()?.OfType<JsonObject>() ?? [])
        {
            if (derived["derivingType"]?.GetValue<string>() != "ref")
            {
                continue;
            }

            var refStructName = derived["refStructName"]?.GetValue<string>();
            if (string.IsNullOrWhiteSpace(refStructName))
            {
                continue;
            }

            if (unionMembers.TryGetValue(refStructName, out var memberNames))
            {
                foreach (var memberName in memberNames)
                {
                    AddInterface(referencedInterfaces, memberName, name);
                }
            }
            else
            {
                AddInterface(referencedInterfaces, refStructName, name);
            }
        }
    }

    return new GenerationContext(unionMembers, referencedInterfaces);
}

static void AddInterface(
    IDictionary<string, HashSet<string>> interfaceMap,
    string typeName,
    string interfaceName)
{
    if (!interfaceMap.TryGetValue(typeName, out var interfaces))
    {
        interfaces = new HashSet<string>(StringComparer.Ordinal);
        interfaceMap[typeName] = interfaces;
    }

    interfaces.Add(interfaceName);
}

static void GenerateCommonStructs(
    string generatedDir,
    JsonArray commonStructs,
    GenerationContext context,
    GeneratorOptions options)
{
    foreach (var item in commonStructs.OfType<JsonObject>())
    {
        var structType = item["structType"]?.GetValue<string>();
        var name = item["name"]?.GetValue<string>() ?? "Unknown";

        if (structType == "simple")
        {
            GenerateSimpleStruct(generatedDir, "Common", name, item["fields"]?.AsArray() ?? [], [], options);
            continue;
        }

        if (structType == "union")
        {
            GenerateUnionStruct(generatedDir, name, item, context, options);
        }
    }
}

static void GenerateApiTypes(string generatedDir, JsonArray categories, GeneratorOptions options)
{
    foreach (var category in categories.OfType<JsonObject>())
    {
        var categoryArea = MapApiCategoryArea(category["name"]?.GetValue<string>() ?? string.Empty);
        foreach (var api in category["apis"]?.AsArray()?.OfType<JsonObject>() ?? [])
        {
            var endpoint = api["endpoint"]?.GetValue<string>() ?? string.Empty;
            if (string.IsNullOrWhiteSpace(endpoint))
            {
                continue;
            }

            var baseName = SnakeToPascal(endpoint);
            if (api["requestFields"] is JsonArray requestFields)
            {
                GenerateSimpleStruct(generatedDir, $"{categoryArea}.Requests", $"{baseName}Request", requestFields, [], options);
            }

            if (api["responseFields"] is JsonArray responseFields)
            {
                GenerateSimpleStruct(generatedDir, $"{categoryArea}.Responses", $"{baseName}Response", responseFields, [], options);
            }
        }
    }
}

static void GenerateUnionStruct(
    string generatedDir,
    string name,
    JsonObject obj,
    GenerationContext context,
    GeneratorOptions options)
{
    const string area = "Common";
    var ns = GetNamespace(area, options);
    var targetDir = GetOutputDirectory(generatedDir, area);
    Directory.CreateDirectory(targetDir);

    var interfacePath = Path.Combine(targetDir, $"{name}.cs");
    WriteFile(interfacePath, $"// <auto-generated />\n#nullable enable\nnamespace {ns};\n\npublic interface {name}\n{{\n}}\n");

    var unionType = obj["unionType"]?.GetValue<string>() ?? "plain";
    if (unionType == "plain")
    {
        foreach (var derived in obj["derivedStructs"]?.AsArray()?.OfType<JsonObject>() ?? [])
        {
            var tagValue = derived["tagValue"]?.GetValue<string>() ?? string.Empty;
            if (string.IsNullOrWhiteSpace(tagValue))
            {
                continue;
            }

            var derivedName = $"{SnakeToPascal(tagValue)}{name}";
            var interfaces = GetInterfaces(context, derivedName, name);
            GenerateSimpleStruct(generatedDir, area, derivedName, derived["fields"]?.AsArray() ?? [], interfaces, options);
        }

        return;
    }

    var baseFields = obj["baseFields"]?.AsArray() ?? [];
    foreach (var derived in obj["derivedTypes"]?.AsArray()?.OfType<JsonObject>() ?? [])
    {
        var derivingType = derived["derivingType"]?.GetValue<string>() ?? "struct";
        if (derivingType != "struct")
        {
            continue;
        }

        var tagValue = derived["tagValue"]?.GetValue<string>() ?? string.Empty;
        if (string.IsNullOrWhiteSpace(tagValue))
        {
            continue;
        }

        var derivedName = $"{SnakeToPascal(tagValue)}{name}";
        var fields = new JsonArray();
        foreach (var field in baseFields)
        {
            fields.Add(field?.DeepClone());
        }

        foreach (var field in derived["fields"]?.AsArray() ?? [])
        {
            fields.Add(field?.DeepClone());
        }

        var interfaces = GetInterfaces(context, derivedName, name);
        GenerateSimpleStruct(generatedDir, area, derivedName, fields, interfaces, options);
    }
}

static IReadOnlyCollection<string> GetInterfaces(GenerationContext context, string typeName, string primaryInterface)
{
    var interfaces = new HashSet<string>(StringComparer.Ordinal) { primaryInterface };
    if (context.ReferencedInterfaces.TryGetValue(typeName, out var additional))
    {
        foreach (var name in additional)
        {
            interfaces.Add(name);
        }
    }

    return interfaces.OrderBy(x => x, StringComparer.Ordinal).ToArray();
}

static void GenerateSimpleStruct(
    string generatedDir,
    string area,
    string name,
    JsonArray fields,
    IReadOnlyCollection<string> implementedInterfaces,
    GeneratorOptions options)
{
    var ns = GetNamespace(area, options);
    var targetDir = GetOutputDirectory(generatedDir, area);
    Directory.CreateDirectory(targetDir);

    var enumDefinitions = CollectEnumDefinitions(name, fields);
    foreach (var enumDefinition in enumDefinitions)
    {
        GenerateEnum(generatedDir, area, enumDefinition, options);
    }

    var members = OrderFieldsForCtor(fields)
        .Select(field => RenderCtorParameter(name, field))
        .ToList();

    var baseClause = implementedInterfaces.Count == 0
        ? string.Empty
        : $" : {string.Join(", ", implementedInterfaces)}";

    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated />");
    sb.AppendLine("#nullable enable");

    var usingNamespaces = GetUsings(area, fields, options);
    foreach (var usingNs in usingNamespaces)
    {
        sb.AppendLine($"using {usingNs};");
    }

    if (usingNamespaces.Count > 0)
    {
        sb.AppendLine();
    }

    sb.AppendLine($"namespace {ns};");
    sb.AppendLine();

    if (members.Count == 0)
    {
        sb.AppendLine($"public sealed partial record {name}{baseClause};");
    }
    else
    {
        sb.AppendLine($"public sealed partial record {name}(");
        for (var i = 0; i < members.Count; i++)
        {
            var suffix = i == members.Count - 1 ? $"){baseClause};" : ",";
            sb.AppendLine($"    {members[i]}{suffix}");
        }
    }

    WriteFile(Path.Combine(targetDir, $"{name}.cs"), sb.ToString());
}

static IReadOnlyList<string> GetUsings(string area, JsonArray fields, GeneratorOptions options)
{
    var usings = new HashSet<string>(StringComparer.Ordinal);
    if (!string.Equals(area, "Common", StringComparison.Ordinal))
    {
        usings.Add(GetNamespace("Common", options));
    }

    foreach (var field in fields.OfType<JsonObject>())
    {
        if (field["isArray"]?.GetValue<bool>() == true)
        {
            usings.Add("System.Collections.Generic");
        }
    }

    return usings.OrderBy(x => x, StringComparer.Ordinal).ToArray();
}

static IReadOnlyList<EnumDefinition> CollectEnumDefinitions(string ownerName, JsonArray fields)
{
    var result = new List<EnumDefinition>();
    foreach (var field in fields.OfType<JsonObject>())
    {
        if (field["fieldType"]?.GetValue<string>() != "enum")
        {
            continue;
        }

        var fieldName = field["name"]?.GetValue<string>() ?? "Unknown";
        var values = field["values"]?.AsArray()?.Select(x => x?.GetValue<string>() ?? string.Empty)
            .Where(x => !string.IsNullOrWhiteSpace(x))
            .ToArray() ?? [];

        result.Add(new EnumDefinition($"{ownerName}{SnakeToPascal(fieldName)}", values));
    }

    return result;
}

static void GenerateEnum(string generatedDir, string area, EnumDefinition enumDefinition, GeneratorOptions options)
{
    var ns = GetNamespace(area, options);
    var targetDir = GetOutputDirectory(generatedDir, area);
    Directory.CreateDirectory(targetDir);

    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated />");
    sb.AppendLine("#nullable enable");
    sb.AppendLine($"namespace {ns};");
    sb.AppendLine();
    sb.AppendLine($"public enum {enumDefinition.Name}");
    sb.AppendLine("{");

    var usedNames = new HashSet<string>(StringComparer.Ordinal);
    for (var i = 0; i < enumDefinition.Values.Count; i++)
    {
        var name = MakeEnumMemberName(enumDefinition.Values[i], usedNames);
        var suffix = i == enumDefinition.Values.Count - 1 ? string.Empty : ",";
        sb.AppendLine($"    {name}{suffix}");
    }

    sb.AppendLine("}");
    WriteFile(Path.Combine(targetDir, $"{enumDefinition.Name}.cs"), sb.ToString());
}

static string MakeEnumMemberName(string value, ISet<string> usedNames)
{
    var candidate = SnakeToPascal(value);
    if (string.IsNullOrWhiteSpace(candidate))
    {
        candidate = "Unknown";
    }

    if (char.IsDigit(candidate[0]))
    {
        candidate = $"Value{candidate}";
    }

    var unique = candidate;
    var index = 2;
    while (!usedNames.Add(unique))
    {
        unique = $"{candidate}{index}";
        index++;
    }

    return unique;
}

static string RenderCtorParameter(string ownerName, JsonObject field)
{
    var type = ResolveFieldType(ownerName, field);
    var name = SnakeToPascal(field["name"]?.GetValue<string>() ?? "Unknown");
    var defaultValue = RenderDefaultValue(ownerName, field);
    return defaultValue is null
        ? $"{type} {name}"
        : $"{type} {name} = {defaultValue}";
}

static IReadOnlyList<JsonObject> OrderFieldsForCtor(JsonArray fields)
{
    return fields
        .OfType<JsonObject>()
        .Select((field, index) => new
        {
            Field = field,
            Index = index,
            IsOptional = IsCtorOptional(field)
        })
        .OrderBy(item => item.IsOptional)
        .ThenBy(item => item.Index)
        .Select(item => item.Field)
        .ToArray();
}

static bool IsCtorOptional(JsonObject field)
{
    if (field["isOptional"]?.GetValue<bool>() == true)
    {
        return true;
    }

    return field.ContainsKey("defaultValue");
}

static string? RenderDefaultValue(string ownerName, JsonObject field)
{
    if (!field.TryGetPropertyValue("defaultValue", out var defaultNode))
    {
        return field["isOptional"]?.GetValue<bool>() == true ? "null" : null;
    }

    if (defaultNode is null)
    {
        return "null";
    }

    var fieldType = field["fieldType"]?.GetValue<string>() ?? "scalar";
    var scalarType = field["scalarType"]?.GetValue<string>() ?? "string";
    var isArray = field["isArray"]?.GetValue<bool>() ?? false;

    if (isArray)
    {
        return defaultNode is JsonArray array && array.Count == 0 ? "[]" : null;
    }

    return fieldType switch
    {
        "scalar" => RenderScalarDefaultValue(defaultNode, scalarType),
        "enum" => RenderEnumDefaultValue(ownerName, field, defaultNode),
        "ref" => "null",
        _ => null
    };
}

static string? RenderScalarDefaultValue(JsonNode defaultNode, string scalarType)
{
    return scalarType switch
    {
        "bool" or "boolean" => defaultNode.GetValue<bool>() ? "true" : "false",
        "int32" => defaultNode.GetValue<int>().ToString(CultureInfo.InvariantCulture),
        "int64" => defaultNode.GetValue<long>().ToString(CultureInfo.InvariantCulture),
        "float32" => $"{defaultNode.GetValue<float>().ToString(CultureInfo.InvariantCulture)}f",
        "float64" => defaultNode.GetValue<double>().ToString(CultureInfo.InvariantCulture),
        "string" => ToCSharpStringLiteral(defaultNode.GetValue<string>()),
        _ => null
    };
}

static string? RenderEnumDefaultValue(string ownerName, JsonObject field, JsonNode defaultNode)
{
    if (defaultNode is not JsonValue)
    {
        return null;
    }

    var enumTypeName = $"{ownerName}{SnakeToPascal(field["name"]?.GetValue<string>() ?? "Unknown")}";
    var enumMemberRaw = defaultNode.GetValue<string>();
    return $"{enumTypeName}.{MakeEnumMemberName(enumMemberRaw, new HashSet<string>(StringComparer.Ordinal))}";
}

static string ToCSharpStringLiteral(string value)
{
    var escaped = value
        .Replace("\\", "\\\\", StringComparison.Ordinal)
        .Replace("\"", "\\\"", StringComparison.Ordinal)
        .Replace("\r", "\\r", StringComparison.Ordinal)
        .Replace("\n", "\\n", StringComparison.Ordinal)
        .Replace("\t", "\\t", StringComparison.Ordinal);

    return $"\"{escaped}\"";
}

static string ResolveFieldType(string ownerName, JsonObject field)
{
    var fieldType = field["fieldType"]?.GetValue<string>() ?? "scalar";
    var isArray = field["isArray"]?.GetValue<bool>() ?? false;
    var isOptional = field["isOptional"]?.GetValue<bool>() ?? false;

    var baseType = fieldType switch
    {
        "scalar" => ResolveScalarType(field["scalarType"]?.GetValue<string>() ?? "string"),
        "enum" => $"{ownerName}{SnakeToPascal(field["name"]?.GetValue<string>() ?? "Unknown")}",
        "ref" => field["refStructName"]?.GetValue<string>() ?? "object",
        _ => "object"
    };

    if (isArray)
    {
        baseType = $"IReadOnlyList<{baseType}>";
    }

    if (isOptional)
    {
        if (baseType.EndsWith("?", StringComparison.Ordinal))
        {
            return baseType;
        }

        return $"{baseType}?";
    }

    return baseType;
}

static string ResolveScalarType(string scalarType) => scalarType switch
{
    "int32" => "int",
    "int64" => "long",
    "float32" => "float",
    "float64" => "double",
    "bool" => "bool",
    "boolean" => "bool",
    "string" => "string",
    "bytes" => "byte[]",
    _ => "string"
};

static string SnakeToPascal(string value)
{
    if (string.IsNullOrWhiteSpace(value))
    {
        return value;
    }

    var builder = new StringBuilder();
    foreach (var rawPart in value.Split('_', StringSplitOptions.RemoveEmptyEntries))
    {
        var part = rawPart.Trim();
        if (part.Length == 0)
        {
            continue;
        }

        builder.Append(char.ToUpperInvariant(part[0]));
        if (part.Length > 1)
        {
            builder.Append(part[1..]);
        }
    }

    return builder.Length == 0 ? "Unknown" : builder.ToString();
}

static string GetNamespace(string area, GeneratorOptions options) => $"{options.RootNamespace}.{area}";

static string GetOutputDirectory(string generatedDir, string area) =>
    Path.Combine([generatedDir, .. area.Split('.')]);

static string MapApiCategoryArea(string categoryName) => categoryName switch
{
    "系统 API" => "System",
    "消息 API" => "Message",
    "好友 API" => "Friend",
    "群聊 API" => "Group",
    "文件 API" => "File",
    _ => "Misc"
};

static void WriteFile(string path, string content)
{
    Directory.CreateDirectory(Path.GetDirectoryName(path)!);
    File.WriteAllText(path, content.Replace("\r\n", "\n"), new UTF8Encoding(false));
}

internal sealed record GenerationContext(
    IReadOnlyDictionary<string, HashSet<string>> UnionMembers,
    IReadOnlyDictionary<string, HashSet<string>> ReferencedInterfaces);

internal sealed record EnumDefinition(string Name, IReadOnlyList<string> Values);

internal sealed record GeneratorOptions(
    string IrUrl,
    string IrSourceName,
    string OutputDirectory,
    string RootNamespace)
{
    public string GeneratedRootNamespace => $"{RootNamespace}.Generated";

    public static GeneratorOptions Parse(string[] args)
    {
        var values = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        for (var i = 0; i < args.Length; i++)
        {
            var key = args[i];
            if (!key.StartsWith("--", StringComparison.Ordinal))
            {
                continue;
            }

            var value = i + 1 < args.Length && !args[i + 1].StartsWith("--", StringComparison.Ordinal)
                ? args[++i]
                : "true";

            values[key] = value;
        }

        var projectRoot = FindProjectRoot();
        var defaultOutput = Path.Combine(projectRoot, "output", "Generated");
        var irUrl = values.GetValueOrDefault("--ir-url") ?? "https://milky.ntqqrev.org/raw/milky-ir/ir.json";
        var irSourceName = values.GetValueOrDefault("--ir-source") ?? "milky-ir/ir.json";
        var outputDirectory = values.GetValueOrDefault("--output");
        var rootNamespace = values.GetValueOrDefault("--namespace") ?? "Milky.Models";

        var resolvedOutputDirectory = string.IsNullOrWhiteSpace(outputDirectory)
            ? defaultOutput
            : Path.GetFullPath(outputDirectory);

        return new GeneratorOptions(
            irUrl,
            irSourceName,
            resolvedOutputDirectory,
            rootNamespace);
    }

    private static string FindProjectRoot()
    {
        var dir = AppContext.BaseDirectory;
        while (!string.IsNullOrEmpty(dir))
        {
            if (File.Exists(Path.Combine(dir, "MilkyModelGenerator.Net.csproj")))
            {
                return dir;
            }

            dir = Directory.GetParent(dir)?.FullName ?? string.Empty;
        }

        return Directory.GetCurrentDirectory();
    }
}
