using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Tomlyn.SourceGeneration;

[Generator]
public sealed class TomlTemplateGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var models = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Tomlyn.TomlModelAttribute",
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol)
            .Collect();

        context.RegisterSourceOutput(models, static (spc, symbols) =>
        {
            foreach (var model in symbols)
            {
                EmitTemplate(spc, model);
            }
        });
    }

    private static void EmitTemplate(SourceProductionContext ctx, INamedTypeSymbol root)
    {
        var toml = new StringBuilder();

        EmitObject(
            sb: toml,
            type: root,
            tableName: null,
            isRoot: true
        );

        var className = root.Name + "_TomlTemplate";

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("namespace GeneratedTomlTemplates");
        source.AppendLine("{");
        source.AppendLine($"    internal static class {className}");
        source.AppendLine("    {");
        source.AppendLine("        public const string Content =");
        source.AppendLine("        \"\"\"");

        var content = toml.ToString().TrimEnd('\r', '\n');

        foreach (var line in content.Split('\n'))
        {
            source.Append("        ");
            source.AppendLine(line);
        }


        source.AppendLine("        \"\"\";");
        source.AppendLine("    }");
        source.AppendLine("}");

        ctx.AddSource($"{className}.g.cs", source.ToString());
    }

    private static void EmitObject(
        StringBuilder sb,
        INamedTypeSymbol type,
        string? tableName,
        bool isRoot)
    {
        // 非根对象才生成 table
        if (!isRoot && tableName != null)
        {
            sb.AppendLine();
            sb.AppendLine($"[{ToTomlKey(tableName)}]");
        }

        foreach (var prop in type.GetMembers().OfType<IPropertySymbol>())
        {
            if (prop.DeclaredAccessibility != Accessibility.Public)
                continue;

            if (IsPrimitive(prop.Type))
            {
                if (TryGetInitializerValue(prop, out var value))
                {
                    sb.AppendLine($"{ToTomlKey(prop.Name)} = {value}");
                }
                else
                {
                    sb.AppendLine(
                        $"{ToTomlKey(prop.Name)} = {FormatDefault(prop)}"
                    );
                }
            }
            else if (HasDefaultCtor(prop.Type))
            {
                EmitObject(
                    sb,
                    (INamedTypeSymbol)prop.Type,
                    prop.Name,
                    isRoot: false
                );
            }
        }
    }

    // =========================
    // 默认值（Syntax 解析）
    // =========================
    private static bool TryGetInitializerValue(
        IPropertySymbol prop,
        out string tomlLiteral)
    {
        tomlLiteral = null!;

        var syntax = prop.DeclaringSyntaxReferences
            .FirstOrDefault()?
            .GetSyntax() as PropertyDeclarationSyntax;

        if (syntax?.Initializer?.Value is not LiteralExpressionSyntax literal)
            return false;

        switch (literal.Kind())
        {
            case SyntaxKind.StringLiteralExpression:
                tomlLiteral = $"\"{literal.Token.ValueText}\"";
                return true;

            case SyntaxKind.TrueLiteralExpression:
                tomlLiteral = "true";
                return true;

            case SyntaxKind.FalseLiteralExpression:
                tomlLiteral = "false";
                return true;

            case SyntaxKind.NumericLiteralExpression:
                tomlLiteral = literal.Token.ValueText;
                return true;

            default:
                return false;
        }
    }

    // =========================
    // 类型判断
    // =========================
    private static bool IsPrimitive(ITypeSymbol type)
        => type.SpecialType switch
        {
            SpecialType.System_String => true,
            SpecialType.System_Boolean => true,
            SpecialType.System_Int32 => true,
            SpecialType.System_Int64 => true,
            SpecialType.System_Double => true,
            SpecialType.System_Decimal => true,
            _ => false
        };

    private static bool HasDefaultCtor(ITypeSymbol type)
        => type is INamedTypeSymbol n &&
           n.InstanceConstructors.Any(c => c.Parameters.Length == 0);

    // =========================
    // 默认值 fallback
    // =========================
    private static string FormatDefault(IPropertySymbol prop)
        => prop.Type.SpecialType switch
        {
            SpecialType.System_String => "\"\"",
            SpecialType.System_Boolean => "false",
            SpecialType.System_Int32 => "0",
            SpecialType.System_Int64 => "0",
            SpecialType.System_Double => "0.0",
            SpecialType.System_Decimal => "0.0",
            _ => "null"
        };

    // =========================
    // 命名规则
    // =========================
    private static string ToTomlKey(string name)
    {
        var sb = new StringBuilder();

        for (int i = 0; i < name.Length; i++)
        {
            var c = name[i];
            if (char.IsUpper(c) && i > 0)
                sb.Append('_');

            sb.Append(char.ToLowerInvariant(c));
        }

        return sb.ToString();
    }
}
